### ISSUE TITLE
Typo in /HedgeDoc-a-New-Fork-of-CodiMD

### ISSUE THREAD

**Issue by Inndy** [CynthiaChuang/CynthiaChuang.github.io#25]
https://cynthiachuang.github.io/HedgeDoc-a-New-Fork-of-CodiMD/

因此基於種種原因，社群版的 CodiMD 後來更名成為 HedgeDoc，並將 `log` 換成一隻可愛小刺蝟。

**Comment by CynthiaChuang** [comment]
df70d6
